services:
  rabbitmq:
    image: rabbitmq:4.0.5-management-alpine
    hostname: rabbitmq
    restart: always
    env_file: "vars_rabbitmq.env.example"      
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  postgres:
    image: postgres:17.2
    restart: always
    hostname: postgres
    env_file: "vars_postgres.env.example"
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  bot_handler:
    build:
      context: /BotHandler/
      dockerfile: Dockerfile-inner
    image: bothandler_inner
    restart: always
    env_file: "vars_spring.env.example"
    develop:
      watch:
        - path: BotHandler/src
          action: rebuild
        - path: BotHandler/build.gradle.kts
          action: rebuild
        - path: BotHandler/settings.gradle.kts
          action: rebuild
        - path: BotHandler/Dockerfile
          action: rebuild
  service:
    build:
      context: /Service/
      dockerfile: Dockerfile-inner
    image: service_inner
    restart: always
    env_file: "vars_spring.env.example"
    ports:
      - 8080:8080
    develop:
      watch:
        - path: Service/src
          action: rebuild
        - path: Service/build.gradle.kts
          action: rebuild
        - path: Service/settings.gradle.kts
          action: rebuild
        - path: Service/Dockerfile
          action: rebuild
  telegram:
    build:
      context: /Bots/TelegramBot
      dockerfile: Dockerfile-inner
    image: telegram_bot_inner
    restart: always
    env_file: "vars_spring.env.example"
    develop:
      watch:
        - path: Bots/TelegramBot/src
          action: rebuild
        - path: Bots/TelegramBot/build.gradle.kts
          action: rebuild
        - path: Bots/TelegramBot/settings.gradle.kts
          action: rebuild
        - path: Bots/TelegramBot/Dockerfile
          action: rebuild
   
